In [20]:
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
%matplotlib inline

# read 데이터
dly = pd.read_csv('AFSNT_DLY.CSV', encoding="cp949")
dly.head()

,SDT_YY,SDT_MM,SDT_DD,SDT_DY,ARP,ODP,FLO,FLT,AOD,STT,DLY,DLY_RATE
0,2019,9,16,월,ARP1,ARP3,L,L1702,A,9:05,NaN,NaN
1,2019,9,16,월,ARP3,ARP1,L,L1702,D,7:55,NaN,NaN
2,2019,9,16,월,ARP1,ARP3,L,L1720,A,14:40,NaN,NaN
3,2019,9,16,월,ARP3,ARP1,L,L1720,D,13:30,NaN,NaN
4,2019,9,16,월,ARP4,ARP3,L,L1808,A,20:10,NaN,NaN

In [21]:
dly.head()

,SDT_YY,SDT_MM,SDT_DD,SDT_DY,ARP,ODP,FLO,FLT,AOD,STT,DLY,DLY_RATE
0,2019,9,16,월,ARP1,ARP3,L,L1702,A,9:05,NaN,NaN
1,2019,9,16,월,ARP3,ARP1,L,L1702,D,7:55,NaN,NaN
2,2019,9,16,월,ARP1,ARP3,L,L1720,A,14:40,NaN,NaN
3,2019,9,16,월,ARP3,ARP1,L,L1720,D,13:30,NaN,NaN
4,2019,9,16,월,ARP4,ARP3,L,L1808,A,20:10,NaN,NaN

In [22]:
dly['hour'] = pd.to_datetime(dly['STT'],format= '%H:%M').dt.hour

In [23]:
import urllib
import json
import pandas as pd
import dateutil.parser
#날씨데이터 json 읽어오는 함수

#나중에 9월 1일을 9월 16일로 바꾼 후 실행..
#(읽어오는거 확인용으로 9월 1일 부터...)
def readJSON(area):
    
    request = urllib.request.urlopen('https://api.aerisapi.com/forecasts/'+area+',korea?from=09/16/2019&format=json&filter=1hr&limit=999&client_id=gHOhinKWCL1fwDUpI1Ec7&client_secret=TRamBTyXpORXcmDKVqc2S4i4mnCjVxxHMt6cllui')
    response = request.read()
    data= json.loads(response)


    if data['success']:
        return data

    else:
        print("An error occurred: %s" % (data['error']['description']))
        return ""
        request.close()

In [24]:
#날씨 csv 저장
def storeWeather():
    weather=pd.DataFrame(columns=['SDT_YY', 'SDT_MM', 'SDT_DD','hour','ARP','temp', 'hum', 'dew', 'windSpeed','hpa'])

    for i in range(15):
        area=["seoul","busan","jeju","daegu","ulsan","cheongju","muan","gwangju","yeosu"
              ,"yangyang","pohang","sacheon","gunsan","wonju","incheon"]
        d=readJSON(area[i])
        response=d['response'][0]
        data=response['periods']
    
    
        for j in range(len(data)):
            temp=data[j]
            date=dateutil.parser.parse(temp['dateTimeISO'])
            temp2=pd.Series([date.year,date.month,date.day,date.hour,"ARP"+str(i+1),temp['tempC'],
                         temp['humidity'],temp['dewpointC'],temp['windGustKTS'],temp['pressureMB']],
                        index=['SDT_YY', 'SDT_MM', 'SDT_DD','hour','ARP','temp', 'hum', 'dew', 'windSpeed','hpa'])
        
            weather=weather.append(temp2,ignore_index=True)
    
    #fog 모델하고의 단위 맞추는 작업
    weather['windSpeed']=weather['windSpeed'].astype("float")*1852/3600
    
    weather.to_csv("newWeather.csv",index=False)

In [25]:
#미래 날씨 데이터 합치기

from datetime import datetime
now=datetime.now()
if now.day>=16:
    we=pd.read_csv('newWeather.csv', encoding="cp949")
    
else:
    print(now.day)
    storeWeather()
    we=pd.read_csv('newWeather.csv', encoding="cp949")

7

In [43]:
final= pd.merge(we, dly, on=['SDT_YY', 'SDT_MM', 'SDT_DD', 'ARP','hour'])
final

#---------------------------------------

,SDT_YY,SDT_MM,SDT_DD,hour,ARP,temp,hum,dew,windSpeed,hpa,SDT_DY,ODP,FLO,FLT,AOD,STT,DLY,DLY_RATE
0,2019,9,16,6,ARP1,20,59,12,2.057778,1013,월,ARP3,L,L1701,D,6:40,NaN,NaN
1,2019,9,16,6,ARP1,20,59,12,2.057778,1013,월,ARP12,J,J1634,D,6:50,NaN,NaN
2,2019,9,16,6,ARP1,20,59,12,2.057778,1013,월,ARP3,F,F1201,D,6:10,NaN,NaN
3,2019,9,16,6,ARP1,20,59,12,2.057778,1013,월,ARP3,F,F1203,D,6:15,NaN,NaN
4,2019,9,16,6,ARP1,20,59,12,2.057778,1013,월,ARP3,J,J1204,D,6:20,NaN,NaN
5,2019,9,16,6,ARP1,20,59,12,2.057778,1013,월,ARP3,A,A1901,D,6:05,NaN,NaN
6,2019,9,16,6,ARP1,20,59,12,2.057778,1013,월,ARP3,H,H1151,D,6:15,NaN,NaN
7,2019,9,16,6,ARP1,20,59,12,2.057778,1013,월,ARP3,F,F1205,D,6:50,NaN,NaN
8,2019,9,16,6,ARP1,20,59,12,2.057778,1013,월,ARP3,A,A1903,D,6:25,NaN,NaN
9,2019,9,16,6,ARP1,20,59,12,2.057778,1013,월,ARP3,H,H1101,D,6:25,NaN,NaN
10,2019,9,16,6,ARP1,20,59,12,2.057778,1013,월,ARP3,B,B1011,D,6:55,NaN,NaN
11,2019,9,16,6,ARP1,20,59,12,2.057778,1013,월,ARP3,A,A1911,D,6:40,NaN,NaN
12,2019,9,16,6,ARP1,20,59,12,2.057778,1013,월,ARP3,I,I1301,D,6:05,NaN,NaN
13,2019,9,16,6,ARP1,20,59,12,2.057778,1013,월,ARP3,I,I1303,D,6:10,NaN,NaN
14,2019,9,16,6,ARP1,20,59,12,2.057778,1013,월,ARP4,B,B1851,D,6:50,NaN,NaN
15,2019,9,16,7,ARP1,21,57,12,2.057778,1013,월,ARP3,L,L1703,D,7:00,NaN,NaN
16,2019,9,16,7,ARP1,21,57,12,2.057778,1013,월,ARP5,B,B1891,D,7:10,NaN,NaN
17,2019,9,16,7,ARP1,21,57,12,2.057778,1013,월,ARP2,B,B1800,A,7:55,NaN,NaN
18,2019,9,16,7,ARP1,21,57,12,2.057778,1013,월,ARP2,B,B1803,D,7:30,NaN,NaN
19,2019,9,16,7,ARP1,21,57,12,2.057778,1013,월,ARP2,J,J1104,D,7:00,NaN,NaN
20,2019,9,16,7,ARP1,21,57,12,2.057778,1013,월,ARP3,A,A1915,D,7:55,NaN,NaN
21,2019,9,16,7,ARP1,21,57,12,2.057778,1013,월,ARP3,A,A1900,A,7:40,NaN,NaN
22,2019,9,16,7,ARP1,21,57,12,2.057778,1013,월,ARP3,A,A1902,A,7:50,NaN,NaN
23,2019,9,16,7,ARP1,21,57,12,2.057778,1013,월,ARP3,J,J1206,D,7:20,NaN,NaN
24,2019,9,16,7,ARP1,21,57,12,2.057778,1013,월,ARP3,H,H1103,D,7:00,NaN,NaN
25,2019,9,16,7,ARP1,21,57,12,2.057778,1013,월,ARP3,B,B1013,D,7:20,NaN,NaN
26,2019,9,16,7,ARP1,21,57,12,2.057778,1013,월,ARP3,H,H1105,D,7:40,NaN,NaN
27,2019,9,16,7,ARP1,21,57,12,2.057778,1013,월,ARP3,A,A1913,D,7:25,NaN,NaN
28,2019,9,16,7,ARP1,21,57,12,2.057778,1013,월,ARP3,I,I1305,D,7:05,NaN,NaN
29,2019,9,16,8,ARP1,22,55,12,2.057778,1013,월,ARP3,L,L1705,D,8:15,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7026,2019,9,20,11,ARP15,20,52,10,2.057778,1015,금,ARP2,J,J1407,A,11:55,NaN,NaN
7027,2019,9,20,14,ARP15,23,43,10,2.572222,1014,금,ARP2,J,J1409,A,14:35,NaN,NaN
7028,2019,9,20,17,ARP15,22,48,10,2.057778,1014,금,ARP2,J,J1411,A,17:40,NaN,NaN
7029,2019,9,20,17,ARP15,22,48,10,2.057778,1014,금,ARP2,A,A1534,A,17:30,NaN,NaN
7030,2019,9,20,17,ARP15,22,48,10,2.057778,1014,금,ARP2,J,J1408,D,17:15,NaN,NaN
7031,2019,9,20,18,ARP15,21,53,11,2.057778,1015,금,ARP2,J,J1406,D,18:25,NaN,NaN
7032,2019,9,20,19,ARP15,20,57,11,2.057778,1015,금,ARP2,A,A1531,D,19:20,NaN,NaN
7033,2019,9,20,19,ARP15,20,57,11,2.057778,1015,금,ARP2,J,J1410,D,19:35,NaN,NaN
7034,2019,9,20,19,ARP15,20,57,11,2.057778,1015,금,ARP4,J,J1416,D,19:35,NaN,NaN
7035,2019,9,21,6,ARP15,18,61,10,1.543333,1016,토,ARP2,A,A1533,D,6:30,NaN,NaN
7036,2019,9,21,8,ARP15,20,55,10,1.543333,1016,토,ARP2,J,J1404,D,8:25,NaN,NaN
7037,2019,9,21,8,ARP15,20,55,10,1.543333,1016,토,ARP2,J,J1405,A,8:10,NaN,NaN
7038,2019,9,21,8,ARP15,20,55,10,1.543333,1016,토,ARP2,A,A1532,A,8:00,NaN,NaN
7039,2019,9,21,8,ARP15,20,55,10,1.543333,1016,토,ARP4,J,J1413,A,8:15,NaN,NaN
7040,2019,9,21,11,ARP15,22,48,11,1.028889,1016,토,ARP2,J,J1407,A,11:55,NaN,NaN
7041,2019,9,21,14,ARP15,25,42,11,1.028889,1015,토,ARP2,J,J1409,A,14:35,NaN,NaN
7042,2019,9,21,17,ARP15,23,50,12,0.514444,1015,토,ARP2,J,J1411,A,17:40,NaN,NaN
7043,2019,9,21,17,ARP15,23,50,12,0.514444,1015,토,ARP2,J,J1408,D,17:15,NaN,NaN
7044,2019,9,21,18,ARP15,22,55,12,0.514444,1016,토,ARP2,J,J1406,D,18:25,NaN,NaN
7045,2019,9,21,19,ARP15,20,60,12,0.514444,1016,토,ARP2,A,A1534,A,19:30,NaN,NaN
7046,2019,9,21,19,ARP15,20,60,12,0.514444,1016,토,ARP2,A,A1531,D,19:20,NaN,NaN
7047,2019,9,21,19,ARP15,20,60,12,0.514444,1016,토,ARP2,J,J1410,D,19:35,NaN,NaN
7048,2019,9,21,19,ARP15,20,60,12,0.514444,1016,토,ARP4,J,J1416,D,19:35,NaN,NaN
7049,2019,9,22,6,ARP15,18,65,11,2.572222,1018,일,ARP2,A,A1533,D,6:30,NaN,NaN
7050,2019,9,22,8,ARP15,19,62,12,3.086667,1018,일,ARP2,A,A1532,A,8:00,NaN,NaN
7051,2019,9,22,8,ARP15,19,62,12,3.086667,1018,일,ARP2,J,J1404,D,8:25,NaN,NaN
7052,2019,9,22,8,ARP15,19,62,12,3.086667,1018,일,ARP2,J,J1405,A,8:10,NaN,NaN
7053,2019,9,22,8,ARP15,19,62,12,3.086667,1018,일,ARP4,J,J1413,A,8:15,NaN,NaN
7054,2019,9,22,9,ARP15,20,60,12,3.086667,1018,일,ARP2,J,J1409,A,9:10,NaN,NaN
7055,2019,9,22,11,ARP15,22,54,12,3.086667,1017,일,ARP2,J,J1407,A,11:55,NaN,NaN

In [44]:
# 파생변수
final['ARPODP'] = final['ARP'] + '_' + final['ODP']

In [45]:
from sklearn import preprocessing
# DLY도 1과 0으로 데이터 처리
le = preprocessing.LabelEncoder()
final[['ARP']] = le.fit_transform(final[['ARP']])
final[['ODP']] = le.fit_transform(final[['ODP']])
final[['FLO']] = le.fit_transform(final[['FLO']])
final[['ARPODP']] = le.fit_transform(final[['ARPODP']])

In [46]:
# 필요없는 column 제거
final.drop(columns=['FLT', 'DLY', 'DLY_RATE'], axis=1, inplace=True)

In [47]:
## Todo: 요일은 계속 원핫???
one_hot_dy = pd.get_dummies(final['SDT_DY'])
final = final.drop(['SDT_DY'],axis = 1)
final = final.join(one_hot_dy)
final.rename(columns={"일":"Sun","월":"Mon","화":"Tue","수":"Wed","목":"Thu","금":"Fri","토":"SAT","일":"Sun"                    
                  }, inplace=True)

In [48]:
# 시간 + 분 합침.
final['time']= (pd.to_datetime(final['STT'],format= '%H:%M').dt.hour).astype(str) + (pd.to_datetime(final['STT'],format= '%H:%M').dt.minute).astype(str)

#dly 스케일링
from sklearn.preprocessing import MinMaxScaler
final['time']= final['time'].astype('int')
scaler = MinMaxScaler()
final[['time']] = scaler.fit_transform(final[['time']])


#예정시각 삭제
final.drop(['STT'], axis = 1, inplace=True)

In [49]:
import warnings
warnings.filterwarnings(action="ignore")

for i in range(5):
    update=[]
    for j in range(24):
        newTemp=0.0
        newHum=0.0
        newDew=0.0
        newWindSpeed=0.0
        newHpa=0.0
        newDew=0.0
        for k in range(5):
            newTemp += final[(final['SDT_DD']==26+i-k+1) & (final['hour']==j)]['temp']
            newHum += final[(final['SDT_DD']==26+i-k+1) & (final['hour']==j)]['hum']
            newDew += final[(final['SDT_DD']==26+i-k+1) & (final['hour']==j)]['dew']
            newWindSpeed += final[(final['SDT_DD']==26+i-k+1) & (final['hour']==j)]['windSpeed']
            newHpa += final[(final['SDT_DD']==26+i-k+1) & (final['hour']==j)]['hpa']
        final[(final['SDT_DD']==26+i) & (final['hour']==j)]['temp']= newTemp / 5
        final[(final['SDT_DD']==26+i) & (final['hour']==j)]['hum']= newHum / 5
        final[(final['SDT_DD']==26+i) & (final['hour']==j)]['dew']= newDew / 5
        final[(final['SDT_DD']==26+i) & (final['hour']==j)]['windSpeed']= newWindSpeed / 5
    
print(final)

      SDT_YY  SDT_MM  SDT_DD  hour  ARP  temp  hum  dew  windSpeed   hpa  ...  \
0       2019       9      16     6    0    20   59   12   2.057778  1013  ...
1       2019       9      16     6    0    20   59   12   2.057778  1013  ...
2       2019       9      16     6    0    20   59   12   2.057778  1013  ...
3       2019       9      16     6    0    20   59   12   2.057778  1013  ...
4       2019       9      16     6    0    20   59   12   2.057778  1013  ...
5       2019       9      16     6    0    20   59   12   2.057778  1013  ...
6       2019       9      16     6    0    20   59   12   2.057778  1013  ...
7       2019       9      16     6    0    20   59   12   2.057778  1013  ...
8       2019       9      16     6    0    20   59   12   2.057778  1013  ...
9       2019       9      16     6    0    20   59   12   2.057778  1013  ...
10      2019       9      16     6    0    20   59   12   2.057778  1013  ...
11      2019       9      16     6    0    20   59   12   2.057778  1013  ...
12      2019       9      16     6    0    20   59   12   2.057778  1013  ...
13      2019       9      16     6    0    20   59   12   2.057778  1013  ...
14      2019       9      16     6    0    20   59   12   2.057778  1013  ...
15      2019       9      16     7    0    21   57   12   2.057778  1013  ...
16      2019       9      16     7    0    21   57   12   2.057778  1013  ...
17      2019       9      16     7    0    21   57   12   2.057778  1013  ...
18      2019       9      16     7    0    21   57   12   2.057778  1013  ...
19      2019       9      16     7    0    21   57   12   2.057778  1013  ...
20      2019       9      16     7    0    21   57   12   2.057778  1013  ...
21      2019       9      16     7    0    21   57   12   2.057778  1013  ...
22      2019       9      16     7    0    21   57   12   2.057778  1013  ...
23      2019       9      16     7    0    21   57   12   2.057778  1013  ...
24      2019       9      16     7    0    21   57   12   2.057778  1013  ...
25      2019       9      16     7    0    21   57   12   2.057778  1013  ...
26      2019       9      16     7    0    21   57   12   2.057778  1013  ...
27      2019       9      16     7    0    21   57   12   2.057778  1013  ...
28      2019       9      16     7    0    21   57   12   2.057778  1013  ...
29      2019       9      16     8    0    22   55   12   2.057778  1013  ...
...      ...     ...     ...   ...  ...   ...  ...  ...        ...   ...  ...
7026    2019       9      20    11    6    20   52   10   2.057778  1015  ...
7027    2019       9      20    14    6    23   43   10   2.572222  1014  ...
7028    2019       9      20    17    6    22   48   10   2.057778  1014  ...
7029    2019       9      20    17    6    22   48   10   2.057778  1014  ...
7030    2019       9      20    17    6    22   48   10   2.057778  1014  ...
7031    2019       9      20    18    6    21   53   11   2.057778  1015  ...
7032    2019       9      20    19    6    20   57   11   2.057778  1015  ...
7033    2019       9      20    19    6    20   57   11   2.057778  1015  ...
7034    2019       9      20    19    6    20   57   11   2.057778  1015  ...
7035    2019       9      21     6    6    18   61   10   1.543333  1016  ...
7036    2019       9      21     8    6    20   55   10   1.543333  1016  ...
7037    2019       9      21     8    6    20   55   10   1.543333  1016  ...
7038    2019       9      21     8    6    20   55   10   1.543333  1016  ...
7039    2019       9      21     8    6    20   55   10   1.543333  1016  ...
7040    2019       9      21    11    6    22   48   11   1.028889  1016  ...
7041    2019       9      21    14    6    25   42   11   1.028889  1015  ...
7042    2019       9      21    17    6    23   50   12   0.514444  1015  ...
7043    2019       9      21    17    6    23   50   12   0.514444  1015  ...
7044    2019       9      21    18    6    22   55   12   0.514444  1016  ...
7045    2019       9      21    19    6    20   60   12   0.514444  1016  ...
7046    2019       9      21    19    6    20   60   12   0.514444  1016  ...
7047    2019       9      21    19    6    20   60   12   0.514444  1016  ...
7048    2019       9      21    19    6    20   60   12   0.514444  1016  ...
7049    2019       9      22     6    6    18   65   11   2.572222  1018  ...
7050    2019       9      22     8    6    19   62   12   3.086667  1018  ...
7051    2019       9      22     8    6    19   62   12   3.086667  1018  ...
7052    2019       9      22     8    6    19   62   12   3.086667  1018  ...
7053    2019       9      22     8    6    19   62   12   3.086667  1018  ...
7054    2019       9      22     9    6    20   60   12   3.086667  1018  ...
7055    2019       9      22    11    6    22   54   12   3.086667  1017  ...

      AOD  ARPODP Fri  Thu  Wed  Mon  Sun  SAT  Tue      time
0       D      12   0    0    0    1    0    0    0  0.266055
1       D      10   0    0    0    1    0    0    0  0.270642
2       D      12   0    0    0    1    0    0    0  0.252294
3       D      12   0    0    0    1    0    0    0  0.254587
4       D      12   0    0    0    1    0    0    0  0.256881
5       D      12   0    0    0    1    0    0    0  0.002294
6       D      12   0    0    0    1    0    0    0  0.254587
7       D      12   0    0    0    1    0    0    0  0.270642
8       D      12   0    0    0    1    0    0    0  0.259174
9       D      12   0    0    0    1    0    0    0  0.259174
10      D      12   0    0    0    1    0    0    0  0.272936
11      D      12   0    0    0    1    0    0    0  0.266055
12      D      12   0    0    0    1    0    0    0  0.002294
13      D      12   0    0    0    1    0    0    0  0.252294
14      D      13   0    0    0    1    0    0    0  0.270642
15      D      12   0    0    0    1    0    0    0  0.004587
16      D      14   0    0    0    1    0    0    0  0.298165
17      A      11   0    0    0    1    0    0    0  0.318807
18      D      11   0    0    0    1    0    0    0  0.307339
19      D      11   0    0    0    1    0    0    0  0.004587
20      D      12   0    0    0    1    0    0    0  0.318807
21      A      12   0    0    0    1    0    0    0  0.311927
22      A      12   0    0    0    1    0    0    0  0.316514
23      D      12   0    0    0    1    0    0    0  0.302752
24      D      12   0    0    0    1    0    0    0  0.004587
25      D      12   0    0    0    1    0    0    0  0.302752
26      D      12   0    0    0    1    0    0    0  0.311927
27      D      12   0    0    0    1    0    0    0  0.305046
28      D      12   0    0    0    1    0    0    0  0.006881
29      D      12   0    0    0    1    0    0    0  0.346330
...   ...     ...  ..  ...  ...  ...  ...  ...  ...       ...
7026    A       7   1    0    0    0    0    0    0  0.502294
7027    A       7   1    0    0    0    0    0    0  0.630734
7028    A       7   1    0    0    0    0    0    0  0.770642
7029    A       7   1    0    0    0    0    0    0  0.766055
7030    D       7   1    0    0    0    0    0    0  0.759174
7031    D       7   1    0    0    0    0    0    0  0.809633
7032    D       7   1    0    0    0    0    0    0  0.853211
7033    D       7   1    0    0    0    0    0    0  0.860092
7034    D       8   1    0    0    0    0    0    0  0.860092
7035    D       7   0    0    0    0    0    1    0  0.261468
7036    D       7   0    0    0    0    0    1    0  0.350917
7037    A       7   0    0    0    0    0    1    0  0.344037
7038    A       7   0    0    0    0    0    1    0  0.009174
7039    A       8   0    0    0    0    0    1    0  0.346330
7040    A       7   0    0    0    0    0    1    0  0.502294
7041    A       7   0    0    0    0    0    1    0  0.630734
7042    A       7   0    0    0    0    0    1    0  0.770642
7043    D       7   0    0    0    0    0    1    0  0.759174
7044    D       7   0    0    0    0    0    1    0  0.809633
7045    A       7   0    0    0    0    0    1    0  0.857798
7046    D       7   0    0    0    0    0    1    0  0.853211
7047    D       7   0    0    0    0    0    1    0  0.860092
7048    D       8   0    0    0    0    0    1    0  0.860092
7049    D       7   0    0    0    0    1    0    0  0.261468
7050    A       7   0    0    0    0    1    0    0  0.009174
7051    D       7   0    0    0    0    1    0    0  0.350917
7052    A       7   0    0    0    0    1    0    0  0.344037
7053    A       8   0    0    0    0    1    0    0  0.346330
7054    A       7   0    0    0    0    1    0    0  0.389908
7055    A       7   0    0    0    0    1    0    0  0.502294

[7056 rows x 22 columns]

In [53]:
# YY랑 DD삭제
final.drop(columns=['SDT_YY', 'SDT_DD'], axis=1, inplace=True)

In [54]:
final.columns

final.drop(columns=['hour'], axis=1, inplace=True)

# 중요도 낮은 변수들 제거

Index(['SDT_MM', 'hour', 'ARP', 'temp', 'hum', 'dew', 'windSpeed', 'hpa',
       'ODP', 'FLO', 'AOD', 'ARPODP', 'Fri', 'Thu', 'Wed', 'Mon', 'Sun', 'SAT',
       'Tue', 'time'],
      dtype='object')

In [ ]:
from sklearn.preprocessing import RobustScaler
import pickle
from sklearn.externals import joblib

def fogModel(df):
    # 날씨 missing 값들은 0으로 대체
    df.fillna(0, inplace = True)
    
    # 모델에서 쓰인 Scaling기법 적용
    scaler = RobustScaler()
    df[['hum', 'dew','temp','windSpeed']] = scaler.fit_transform(df[['hum', 'dew','temp','windSpeed']])
    
    # 저장된 모델 불러오기
    clf_from_joblib = joblib.load('fogmodel.pkl') 

    # 지연 율 저장
    fog_prob = clf_from_joblib.predict_proba(df)
    

    fog_column = []
    # dly_rate에 지연율 저장
    for i in fog_prob:
        fog_column.append(i[1])
        
    
    return fog_column

In [ ]:
# df에서 fog관련 column만 함수에 넘김
fog = final[["temp","hum","dew","windSpeed"]]

fog_column = fogModel(fog)

In [ ]:
# 안개 column 추가
final['fog'] = fog_column

# 안개 관련 column 제거
final.drop(columns=['hum', 'dew','temp','windSpeed'], axis=1, inplace=True)
final.head()

In [ ]:
# 도착, 출발 데이터 분리
final_A = final[final['AOD']=='A']
final_D = final[final['AOD']=='D']

# AOD column삭제 
final_A = final_A.drop(['AOD'],axis = 1)
final_D = final_D.drop(['AOD'],axis = 1)

In [ ]:
# ------------------------------ #

In [ ]:
########## 아직 저장된 모델이 없음

# df_A 모델 -----------------------------------------------

# df_A 모델 불러오기
predict_dealy_A_joblib = joblib.load('predict_delay_A.pkl') 

# DLY 저장하기
dly_A = predict_dealy_A_joblib.predict(final_A)

# DLY_RATE 저장하기
dly_A_prob = predict_dealy_A_joblib.predict_proba(final_A)

dly_rate_A = []

# dly_rate에 지연율 저장
for i in dly_A_prob:
    dly_rate_A.append(i[1])
    
# DateFrame에 DLY, DLY_RATE추가
final.loc[dly['AOD']=='A','DLY'] = dly_A
final.loc[dly['AOD']=='A','DLY_RATE'] = dly_rate_A

# ---------------------------------------------------------

In [ ]:
# df_D 모델 -----------------------------------------------

# df_D 모델 불러오기
predict_dealy_D_joblib = joblib.load('predict_delay_D.pkl') 

# DLY 저장하기
dly_D = predict_dealy_D_joblib.predict(df_D)

# DLY_RATE 저장하기
dly_A_prob = predict_dealy_A_joblib.predict_proba(df_D)

dly_rate_D = []

# dly_rate에 지연율 저장
for i in dly_D_prob:
    dly_rate_D.append(i[1])
    
# DateFrame에 DLY, DLY_RATE추가
final.loc[dly['AOD']=='D','DLY'] = dly_D
final.loc[dly['AOD']=='D','DLY_RATE'] = dly_rate_D

# ---------------------------------------------------------

In [ ]:
# 라벨을 1,0에서 -> Y,N으로 
final.loc[dly['DLY']==1,'DLY'] = 'Y'
final.loc[dly['DLY']==0,'DLY'] = 'N'